#!/bin/tcsh
#PBS -l nodes=1:ppn=8
#PBS -q workq
#PBS -r n
#PBS -l walltime=48:00:00
#PBS -N spec_test_mpi

module load intel/intel-12.1.5
module load openmpi/1.6.1-intel-12.1.5
module load fftw/3.3.2-intel-12.1.5-openmpi-1.6.1

cd $PBS_O_WORKDIR
#
setenv OMP_NUM_THREADS 1
make spectral
time mpirun runspec > log.out
