#!/bin/tcsh
#PBS -l nodes=32:ppn=8
#PBS -q workq
#PBS -r n
#PBS -l walltime=48:00:00
#PBS -N bubbles_exact_profile

module unload fftw
module unload openmpi
module unload intel

module load intel/intel-12.1.5
module load openmpi/1.6.1-intel-12.1.5
module load fftw/3.3.2-intel-12.1.5-openmpi-1.6.1

#cd /mnt/scratch-lustre/jbraden/bubble_collisions/collision_exact_ic_1024_wline/
cd $PBS_O_WORKDIR
#
time mpirun defrost > log.out
